name: Build CLI from Version Variable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Read version from Chat_Client.py
        id: read_version
        run: |
          VNUM=$(python -c "from Chat_Client import vnum; print(vnum)")
          echo "VERSION=$VNUM" >> $GITHUB_ENV

      - name: Build exe
        run: |
          pyinstaller --onefile Chat_Client.py --name "ChatClient-${{ env.VERSION }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: dist/ChatClient-${{ env.VERSION }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version.json in website repo
        uses: actions/checkout@v4
        with:
          repository: Bapt-Tech/chatver
          token: ${{ secrets.GH_PAT }}
          path: website
      - name: Update version.json
        run: |
          echo "{\"latest_version\": \"${{ env.VERSION }}\", \"download_url\": \"https://github.com/Bapt-Tech/chatver/releases/download/${{ env.VERSION }}/my-cli-${{ env.VERSION }}.exe\"}" > website/docs/version.json
          cd website
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/version.json
          git commit -m "Update version to ${{ env.VERSION }}"
          git push
